[package]
name = "wzp-video"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
shiguredo_video_toolbox = "2026.1"

[dev-dependencies]
rand = "0.8"
